Custom exception for buffer over/underflow
EsotericSoftware/kryo pull request #874
Opened 2021-12-29 20:46 UTC by msx80

Implements #872

2021-12-30 11:09 UTC, theigl commented
@msx80: Thanks a lot for the PR! 

Please apply `mvn formatter:format` on the PR, so we can be sure it adheres to the project code style.

Since this is affecting the public API, I'll try to get feedback from the project's original author.

2021-12-30 11:11 UTC, theigl requested changes

2021-12-30 11:11 UTC, theigl commented on test/com/esotericsoftware/kryo/io/ByteBufferInputOutputTest.java
> +	void testOverflow () {
Please use JUnit 5 style assertions for exceptions:

https://stackoverflow.com/a/40268447/441266

2022-01-03 15:22 UTC, msx80 commented
should be ok now

2022-01-18 17:54 UTC, theigl commented
@msx80: Thank you for your patience! 

I finally found the time to get some feedback. We only need one minor change to your PR: Please remove the `KryoIOException` superclass. We don't really need it at the moment and can add it back anytime, should somebody ask for it. Then I'll merge the PR.

2022-01-19 10:59 UTC, msx80 commented
i've removed it, let me know if it's ok thank you :)

2022-01-20 15:12 UTC, theigl approved these changes

2022-01-20 15:20 UTC, merged

2022-01-20 15:21 UTC, theigl commented
Merged, thank you @msx80!